version: "3.3"
services:
  web:
    image: faraquet/cherry-pdf:0.0.1
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    ports:
      - '3003:3000'
    environment:
      TOKEN_AUTHENTICATABLE: "false"

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
