version: "3.3"
services:
  web:
    image: faraquet/cherry-api:0.0.6
    build:
      context: .
      args:
        RUBY_VERSION: '3.4'
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    platform: linux/amd64  # Force AMD64 platform
    ports:
      - '3003:3000'
    env_file:
      - .env
volumes:
  bundle:
  rails_cache:
