name: RSpec

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install SQLite3
        run: gem install sqlite3

      - name: Setup Database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run RSpec
        env:
          RAILS_ENV: test
        run: bundle exec rspec
